### ISSUE TITLE
Genesis & bootstrap configuration for system tokens

### ISSUE THREAD

**Issue by energyGiver** [InfraBlockchain/infra-cumulus#38]
## Overview
- Relay chain and statemint parachain are needed to set up in the cumulus zombienet config.
- Two system tokens(iKRW, iUSD) are issued and minted by the statemine.
- Only asset related pallet would be accepted as a transaction fee in the infrablockspace, not balance.
- Sudo pallet and Sudo(root) account are required for bootstraping.

## Todo
- [x] Relay chain(4 validators) and statemint parachain(2 collators) are set up in the cumulus zombienet config.
    - The chain_spec of "infrabs" should be initialized.
- [x] Two system tokens(iKRW, iUSD) are issued and minted by the statemine.
    - iKRW: asset_id = 1, min_balance = 1300, is_sufficient=true, ...
    - iUSD: asset_id = 2, min_balance = 1, is_sufficient=true, ...
- [x] Sudo pallet and sudo(root) account are set up for bootstraping.
    - On the local test network, each chain should have a sudo pallet and at least one root account.
- [ ] Those tokens are globally identified among relay and all parachains using XCM asset registry.
    - To be implemeted
- [ ] The asset-related pallet should take over the functionality of the balance-related pallet. 
    - To be implemeted

**Comment by energyGiver** [comment]
closed as this issue is merged
